version: "3.5"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx-server
    ports:
      - "3030:80"
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres_password
  redis:
    container_name: "microservice-transport-layer"
    image: "redis:6.2-alpine"
    ports:
      - 6379:6379
  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./microservices
    volumes:
      - /app/node_modules
      - ./microservices:/app
volumes:
  app:
