FROM node:14.17.0
WORKDIR '/app'
COPY package.json yarn.lock ./
COPY packages/gateway-service/package.json /app/packages/gateway-service/package.json
COPY packages/calendar-service/package.json /app/packages/calendar-service/package.json
# COPY packages/task-service/package.json /app/packages/task-service/package.json
COPY lerna.json /app/lerna.json
RUN yarn
COPY . .

CMD ["yarn","run","start:dev"]
